
import javax.swing.Timer;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jyoti
 */
public class HomePage extends javax.swing.JFrame  {

    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        allBuses = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Occasion = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        route = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jButton24 = new javax.swing.JButton();
        search = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton18 = new javax.swing.JButton();
        cancel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        Cancel_UserID = new javax.swing.JTextField();
        reviews = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane_Review = new javax.swing.JScrollPane();
        review_area = new javax.swing.JTextArea();
        jButton16 = new javax.swing.JButton();
        rent = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jText_UserID = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jCombo_No = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jText_Date = new javax.swing.JTextField();
        jButton23 = new javax.swing.JButton();
        gymkhanaBooking = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        stop = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jButton25 = new javax.swing.JButton();
        departmentBooking = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        socultBooking = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        societyBooking = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton22 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1380, 800));
        setSize(new java.awt.Dimension(1380, 800));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(10, 168, 246));
        jPanel1.setMinimumSize(new java.awt.Dimension(1380, 110));
        jPanel1.setPreferredSize(new java.awt.Dimension(1380, 110));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/bali007/NetBeansProjects/Bus_Information_System_New/Photos/Head_IIT.png")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1380, 80));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 10, 1250, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1380, 110);

        jPanel2.setBackground(new java.awt.Color(19, 80, 127));
        jPanel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(19, 80, 127));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton1.setText("Home");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(0, 0, 200, 33);

        jPanel4.setBackground(new java.awt.Color(19, 80, 127));
        jPanel4.setLayout(null);

        jButton2.setBackground(new java.awt.Color(190, 187, 201));
        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton2.setText("Buses from Stop");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(0, 120, 200, 30);

        jButton4.setBackground(new java.awt.Color(190, 187, 201));
        jButton4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton4.setText("Start-Stop");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(0, 30, 200, 33);

        jButton5.setBackground(new java.awt.Color(190, 187, 201));
        jButton5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton5.setText("Stops on Route");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(0, 60, 200, 30);

        jButton6.setBackground(new java.awt.Color(190, 187, 201));
        jButton6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton6.setText("All Routes");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(0, 90, 200, 30);

        jButton3.setBackground(new java.awt.Color(19, 80, 127));
        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton3.setText("SEARCH  >>");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(0, 0, 200, 33);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 30, 200, 30);

        jPanel6.setBackground(new java.awt.Color(19, 80, 127));
        jPanel6.setLayout(null);

        jButton7.setBackground(new java.awt.Color(19, 80, 127));
        jButton7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton7.setText("BOOKING >>");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7);
        jButton7.setBounds(0, 0, 200, 30);

        jButton8.setBackground(new java.awt.Color(190, 187, 201));
        jButton8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton8.setText("Departmental");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8);
        jButton8.setBounds(0, 30, 200, 30);

        jButton9.setBackground(new java.awt.Color(190, 187, 201));
        jButton9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton9.setText("Gymkhana Events");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9);
        jButton9.setBounds(0, 60, 200, 30);

        jButton10.setBackground(new java.awt.Color(190, 187, 201));
        jButton10.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton10.setText("Sports & Cultural");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10);
        jButton10.setBounds(0, 90, 200, 30);

        jButton11.setBackground(new java.awt.Color(190, 187, 201));
        jButton11.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton11.setText("Societies");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton11);
        jButton11.setBounds(0, 120, 200, 30);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(0, 60, 200, 30);

        jButton12.setBackground(new java.awt.Color(19, 80, 127));
        jButton12.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton12.setText("Renting");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12);
        jButton12.setBounds(0, 120, 200, 30);

        jButton13.setBackground(new java.awt.Color(19, 80, 127));
        jButton13.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton13.setText("Cancellation");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13);
        jButton13.setBounds(0, 150, 200, 30);

        jButton14.setBackground(new java.awt.Color(19, 80, 127));
        jButton14.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton14.setText("Reviews");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14);
        jButton14.setBounds(0, 180, 200, 30);

        jButton15.setBackground(new java.awt.Color(19, 80, 127));
        jButton15.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton15.setText("Occasional Buses");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15);
        jButton15.setBounds(0, 90, 200, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 110, 200, 700);

        jPanel5.setLayout(null);

        home.setBackground(new java.awt.Color(203, 199, 196));
        home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 22, 111), 10));
        home.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/bali007/NetBeansProjects/Bus_Information_System_New/Photos/bus.jpg")); // NOI18N
        jLabel3.setMinimumSize(new java.awt.Dimension(200, 100));
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 100));
        home.add(jLabel3);
        jLabel3.setBounds(40, 40, 600, 310);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel10.setText("News Feeds ...");
        home.add(jLabel10);
        jLabel10.setBounds(670, 48, 330, 300);
        home.add(jLabel11);
        jLabel11.setBounds(47, 360, 970, 250);

        jPanel5.add(home);
        home.setBounds(0, 0, 1050, 640);

        allBuses.setBackground(new java.awt.Color(203, 199, 196));
        allBuses.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 22, 111), 10));
        allBuses.setLayout(null);

        jLabel40.setFont(new java.awt.Font("Ubuntu", 3, 48)); // NOI18N
        jLabel40.setText("All Buses");
        allBuses.add(jLabel40);
        jLabel40.setBounds(210, 10, 380, 120);

        jLabel6.setText("Note :-  \"Empty Block\" means the bus is not running through that stop!");
        allBuses.add(jLabel6);
        jLabel6.setBounds(120, 130, 530, 18);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Bus No.", "Route No.", "Stop a", "Stop b", "Stop c", "Stop d", "Stop e", "Stop f", "Stop g", "Stop h"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        allBuses.add(jScrollPane2);
        jScrollPane2.setBounds(120, 150, 790, 140);

        jPanel5.add(allBuses);
        allBuses.setBounds(0, 0, 1050, 640);

        Occasion.setBackground(new java.awt.Color(203, 199, 196));
        Occasion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 22, 111), 10));
        Occasion.setLayout(null);

        jLabel38.setFont(new java.awt.Font("Ubuntu", 3, 48)); // NOI18N
        jLabel38.setText("Ocassional Buses..");
        Occasion.add(jLabel38);
        jLabel38.setBounds(210, 50, 550, 120);

        jLabel39.setText("Following is a list of dates on which there will be buses running between IIT Kgp and railway Station");
        Occasion.add(jLabel39);
        jLabel39.setBounds(90, 160, 700, 18);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Occasion.add(jScrollPane1);
        jScrollPane1.setBounds(90, 190, 200, 140);

        jPanel5.add(Occasion);
        Occasion.setBounds(0, 0, 1050, 640);

        route.setBackground(new java.awt.Color(203, 199, 196));
        route.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 22, 111), 10));
        route.setLayout(null);

        jLabel36.setFont(new java.awt.Font("Ubuntu", 3, 48)); // NOI18N
        jLabel36.setText("Search by route no.");
        route.add(jLabel36);
        jLabel36.setBounds(210, 50, 550, 120);

        jLabel4.setText("Enter Route no.");
        route.add(jLabel4);
        jLabel4.setBounds(70, 190, 140, 18);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        route.add(jComboBox8);
        jComboBox8.setBounds(250, 180, 49, 28);

        jButton24.setText("SEARCH");
        route.add(jButton24);
        jButton24.setBounds(490, 180, 68, 30);

        jPanel5.add(route);
        route.setBounds(0, 0, 1050, 640);

        search.setBackground(new java.awt.Color(203, 199, 196));
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 22, 111), 10));
        search.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Ubuntu", 3, 48)); // NOI18N
        jLabel16.setText("Search By Start -Stop");
        search.add(jLabel16);
        jLabel16.setBounds(210, 50, 550, 120);

        jLabel8.setText("Stop Point");
        search.add(jLabel8);
        jLabel8.setBounds(80, 280, 100, 18);

        jLabel17.setText("Start Point");
        search.add(jLabel17);
        jLabel17.setBounds(80, 200, 100, 18);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S_a", "S_b", "S_c", "S_d", "S_e", "S_f", "S_g", "S_h" }));
        search.add(jComboBox1);
        jComboBox1.setBounds(230, 270, 62, 28);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S_a", "S_b", "S_c", "S_d", "S_e", "S_f", "S_g", "S_h" }));
        search.add(jComboBox2);
        jComboBox2.setBounds(230, 200, 62, 28);

        jButton18.setText("SUBMIT");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        search.add(jButton18);
        jButton18.setBounds(470, 220, 180, 30);

        jPanel5.add(search);
        search.setBounds(0, 0, 1050, 640);

        cancel.setBackground(new java.awt.Color(203, 199, 196));
        cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 22, 111), 10));
        cancel.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 3, 48)); // NOI18N
        jLabel13.setText("CANCELLATION");
        cancel.add(jLabel13);
        jLabel13.setBounds(210, 50, 380, 120);

        jLabel14.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel14.setText("Enter BOOKING/RENTING Reference no.");
        cancel.add(jLabel14);
        jLabel14.setBounds(80, 210, 380, 21);

        jButton17.setBackground(new java.awt.Color(40, 151, 10));
        jButton17.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton17.setText("Submit Request");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        cancel.add(jButton17);
        jButton17.setBounds(90, 350, 220, 33);

        Cancel_UserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_UserIDActionPerformed(evt);
            }
        });
        cancel.add(Cancel_UserID);
        Cancel_UserID.setBounds(90, 270, 270, 28);

        jPanel5.add(cancel);
        cancel.setBounds(0, 0, 1050, 640);

        reviews.setBackground(new java.awt.Color(203, 199, 196));
        reviews.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 22, 111), 10));
        reviews.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 3, 48)); // NOI18N
        jLabel9.setText("REVIEWS !!!");
        reviews.add(jLabel9);
        jLabel9.setBounds(210, 50, 380, 120);

        jLabel12.setText("Write in no more than 100 words ...");
        reviews.add(jLabel12);
        jLabel12.setBounds(60, 180, 300, 18);

        review_area.setColumns(20);
        review_area.setRows(5);
        jScrollPane_Review.setViewportView(review_area);

        reviews.add(jScrollPane_Review);
        jScrollPane_Review.setBounds(70, 220, 630, 360);

        jButton16.setBackground(new java.awt.Color(221, 26, 149));
        jButton16.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton16.setText("SUBMIT REVIEW");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        reviews.add(jButton16);
        jButton16.setBounds(750, 350, 170, 60);

        jPanel5.add(reviews);
        reviews.setBounds(0, 0, 1050, 640);

        rent.setBackground(new java.awt.Color(203, 199, 196));
        rent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 22, 111), 10));
        rent.setLayout(null);

        jLabel32.setFont(new java.awt.Font("Ubuntu", 3, 48)); // NOI18N
        jLabel32.setText("Rent Buses");
        rent.add(jLabel32);
        jLabel32.setBounds(210, 50, 550, 120);

        jLabel33.setText("User ID :");
        rent.add(jLabel33);
        jLabel33.setBounds(90, 210, 90, 18);
        rent.add(jText_UserID);
        jText_UserID.setBounds(310, 200, 200, 28);

        jLabel34.setText("no. of Buses:");
        rent.add(jLabel34);
        jLabel34.setBounds(90, 260, 120, 18);

        jCombo_No.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        rent.add(jCombo_No);
        jCombo_No.setBounds(310, 260, 46, 28);

        jLabel35.setText("Date (DD-MM-YYYY)");
        rent.add(jLabel35);
        jLabel35.setBounds(90, 320, 180, 18);
        rent.add(jText_Date);
        jText_Date.setBounds(310, 310, 150, 28);

        jButton23.setText("SUBMIT");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        rent.add(jButton23);
        jButton23.setBounds(220, 430, 130, 30);

        jPanel5.add(rent);
        rent.setBounds(0, 0, 1050, 640);

        gymkhanaBooking.setBackground(new java.awt.Color(203, 199, 196));
        gymkhanaBooking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 22, 111), 10));
        gymkhanaBooking.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Ubuntu", 3, 48)); // NOI18N
        jLabel15.setText("Booking By Gymkhana");
        gymkhanaBooking.add(jLabel15);
        jLabel15.setBounds(210, 50, 550, 120);

        jLabel5.setText("User ID :");
        gymkhanaBooking.add(jLabel5);
        jLabel5.setBounds(90, 210, 90, 18);
        gymkhanaBooking.add(jTextField2);
        jTextField2.setBounds(310, 200, 200, 28);

        jLabel18.setText("no. of Buses:");
        gymkhanaBooking.add(jLabel18);
        jLabel18.setBounds(90, 260, 120, 18);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        gymkhanaBooking.add(jComboBox3);
        jComboBox3.setBounds(310, 260, 46, 28);

        jLabel19.setText("Date (DD-MM-YYYY)");
        gymkhanaBooking.add(jLabel19);
        jLabel19.setBounds(90, 320, 180, 18);
        gymkhanaBooking.add(jTextField3);
        jTextField3.setBounds(310, 310, 150, 28);

        jButton19.setText("SUBMIT");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        gymkhanaBooking.add(jButton19);
        jButton19.setBounds(220, 430, 130, 30);

        jPanel5.add(gymkhanaBooking);
        gymkhanaBooking.setBounds(0, 0, 1050, 640);

        stop.setBackground(new java.awt.Color(203, 199, 196));
        stop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 22, 111), 10));
        stop.setLayout(null);

        jLabel37.setFont(new java.awt.Font("Ubuntu", 3, 48)); // NOI18N
        jLabel37.setText("Search by stop");
        stop.add(jLabel37);
        jLabel37.setBounds(210, 50, 550, 120);

        jLabel7.setText("Enter Stop");
        stop.add(jLabel7);
        jLabel7.setBounds(70, 190, 140, 18);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S_a", "S_b", "S_c", "S_d", "S_e", "S_f", "S_g", "S_h", " " }));
        stop.add(jComboBox9);
        jComboBox9.setBounds(250, 180, 62, 28);

        jButton25.setText("SEARCH");
        stop.add(jButton25);
        jButton25.setBounds(490, 180, 68, 30);

        jPanel5.add(stop);
        stop.setBounds(0, 0, 1050, 640);

        departmentBooking.setBackground(new java.awt.Color(203, 199, 196));
        departmentBooking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 22, 111), 10));
        departmentBooking.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Ubuntu", 3, 48)); // NOI18N
        jLabel20.setText("Booking By Departments");
        departmentBooking.add(jLabel20);
        jLabel20.setBounds(210, 50, 550, 120);
        jLabel20.getAccessibleContext().setAccessibleName("Departmental Booking");

        jLabel21.setText("User ID :");
        departmentBooking.add(jLabel21);
        jLabel21.setBounds(90, 210, 90, 18);
        departmentBooking.add(jTextField4);
        jTextField4.setBounds(310, 200, 200, 28);

        jLabel22.setText("no. of Buses:");
        departmentBooking.add(jLabel22);
        jLabel22.setBounds(90, 260, 120, 18);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        departmentBooking.add(jComboBox4);
        jComboBox4.setBounds(310, 260, 46, 28);

        jLabel23.setText("Date (DD-MM-YYYY)");
        departmentBooking.add(jLabel23);
        jLabel23.setBounds(90, 320, 180, 18);
        departmentBooking.add(jTextField5);
        jTextField5.setBounds(310, 310, 150, 28);

        jButton20.setText("SUBMIT");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        departmentBooking.add(jButton20);
        jButton20.setBounds(220, 430, 130, 30);

        jPanel5.add(departmentBooking);
        departmentBooking.setBounds(0, 0, 1050, 640);

        socultBooking.setBackground(new java.awt.Color(203, 199, 196));
        socultBooking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 22, 111), 10));
        socultBooking.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Ubuntu", 3, 48)); // NOI18N
        jLabel24.setText("Booking For Events");
        socultBooking.add(jLabel24);
        jLabel24.setBounds(210, 50, 550, 120);
        jLabel24.getAccessibleContext().setAccessibleName("Booking for SoCult Events");

        jLabel26.setText("User ID :");
        socultBooking.add(jLabel26);
        jLabel26.setBounds(90, 210, 90, 18);
        socultBooking.add(jTextField6);
        jTextField6.setBounds(310, 200, 200, 28);

        jLabel28.setText("no. of Buses:");
        socultBooking.add(jLabel28);
        jLabel28.setBounds(90, 260, 120, 18);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        socultBooking.add(jComboBox5);
        jComboBox5.setBounds(310, 260, 46, 28);

        jLabel30.setText("Date (DD-MM-YYYY)");
        socultBooking.add(jLabel30);
        jLabel30.setBounds(90, 320, 180, 18);
        socultBooking.add(jTextField8);
        jTextField8.setBounds(310, 310, 150, 28);

        jButton21.setText("SUBMIT");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        socultBooking.add(jButton21);
        jButton21.setBounds(220, 430, 130, 30);

        jPanel5.add(socultBooking);
        socultBooking.setBounds(0, 0, 1050, 640);

        societyBooking.setBackground(new java.awt.Color(203, 199, 196));
        societyBooking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 22, 111), 10));
        societyBooking.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Ubuntu", 3, 48)); // NOI18N
        jLabel25.setText("Booking By Society");
        societyBooking.add(jLabel25);
        jLabel25.setBounds(210, 50, 550, 120);
        jLabel25.getAccessibleContext().setAccessibleName("Booking By Societies");

        jLabel27.setText("User ID :");
        societyBooking.add(jLabel27);
        jLabel27.setBounds(90, 210, 90, 18);
        societyBooking.add(jTextField7);
        jTextField7.setBounds(310, 200, 200, 28);

        jLabel29.setText("no. of Buses:");
        societyBooking.add(jLabel29);
        jLabel29.setBounds(90, 260, 120, 18);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        societyBooking.add(jComboBox6);
        jComboBox6.setBounds(310, 260, 46, 28);

        jLabel31.setText("Date (DD-MM-YYYY)");
        societyBooking.add(jLabel31);
        jLabel31.setBounds(90, 320, 180, 18);
        societyBooking.add(jTextField9);
        jTextField9.setBounds(310, 310, 150, 28);

        jButton22.setText("SUBMIT");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        societyBooking.add(jButton22);
        jButton22.setBounds(220, 430, 130, 30);

        jPanel5.add(societyBooking);
        societyBooking.setBounds(0, 0, 1050, 640);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(230, 140, 1040, 660);

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/bali007/NetBeansProjects/Bus_Information_System_New/Photos/Body_Login.png")); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1380, 800));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 40, 1380, 800);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(210, 110, 10, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        
        jPanel5.add(stop);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        
        jPanel5.add(allBuses);
        jPanel5.repaint();
        jPanel5.revalidate();
        
        
        conn = MyConnection.getConnection();
          try
          {
              String query  = "SELECT * FROM  Bus_info";
              ps = conn.prepareStatement(query);
              ResultSet rs = ps.executeQuery();
              
              jTable2.setModel(DbUtils.resultSetToTableModel(rs)); 
          }
          catch(Exception e)
          {
              JOptionPane.showMessageDialog(null,e);
          }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        
        jPanel5.add(departmentBooking);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        
        jPanel5.add(gymkhanaBooking);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        
        jPanel5.add(socultBooking);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        
        jPanel5.add(societyBooking);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        
        jPanel5.add(rent);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        
        jPanel5.add(cancel);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        
        jPanel5.add(reviews);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void DisplayTable()
    {
        conn = MyConnection.getConnection();
          try
          {
              String query  = "SELECT * FROM  Ocassion";
              ps = conn.prepareStatement(query);
              ResultSet rs = ps.executeQuery();
              
              jTable1.setModel(DbUtils.resultSetToTableModel(rs)); 
          }
          catch(Exception e)
          {
              JOptionPane.showMessageDialog(null,e);
          }
            
    }
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        
        jPanel5.add(Occasion);
        jPanel5.repaint();
        jPanel5.revalidate();
        
        DisplayTable();
        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:\
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        
        jPanel5.add(home);
        jPanel5.repaint();
        jPanel5.revalidate();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
         // TODO add your handling code here:
//         jPanel6.setSize(jPanel6.getWidth(),30);
//         jPanel4.setSize(jPanel4.getWidth(),150);
         //t1.start();
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        //t1.stop();
        
        //p1=30;
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        // TODO add your handling code here:
//        jPanel4.setSize(jPanel4.getWidth(),30);
//        jPanel6.setSize(jPanel6.getWidth(),150);
        //t2.start();
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        // TODO add your handling code here:
        //t2.stop();
        //p2=30;
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        jPanel6.setSize(jPanel6.getWidth(),30);
        jPanel4.setSize(jPanel4.getWidth(),150);
        jButton12.setBounds(0, 120+3*30, 200, 30);
        jButton13.setBounds(0, 150+3*30, 200, 30);
        jButton14.setBounds(0, 180+3*30, 200, 30);
        jButton15.setBounds(0, 90+3*30, 200, 30);
        
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        jPanel4.setSize(jPanel4.getWidth(),30);
        jPanel6.setSize(jPanel6.getWidth(),150);
        jButton12.setBounds(0, 120+4*30, 200, 30);
        jButton13.setBounds(0, 150+4*30, 200, 30);
        jButton14.setBounds(0, 180+4*30, 200, 30);
        jButton15.setBounds(0, 90+4*30, 200, 30);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jPanel6.setSize(jPanel6.getWidth(),30);
        jPanel4.setSize(jPanel4.getWidth(),30);
        jButton12.setBounds(0, 120, 200, 30);
        jButton13.setBounds(0, 150, 200, 30);
        jButton14.setBounds(0, 180, 200, 30);
        jButton15.setBounds(0, 90, 200, 30);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // TODO add your handling code here:
        jPanel6.setSize(jPanel6.getWidth(),30);
        jPanel4.setSize(jPanel4.getWidth(),30);
        jButton12.setBounds(0, 120, 200, 30);
        jButton13.setBounds(0, 150, 200, 30);
        jButton14.setBounds(0, 180, 200, 30);
        jButton15.setBounds(0, 90, 200, 30);
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        jPanel6.setSize(jPanel6.getWidth(),30);
        jPanel4.setSize(jPanel4.getWidth(),30);
        jButton12.setBounds(0, 120, 200, 30);
        jButton13.setBounds(0, 150, 200, 30);
        jButton14.setBounds(0, 180, 200, 30);
        jButton15.setBounds(0, 90, 200, 30);
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
        jPanel6.setSize(jPanel6.getWidth(),30);
        jPanel4.setSize(jPanel4.getWidth(),30);
        jButton12.setBounds(0, 120, 200, 30);
        jButton13.setBounds(0, 150, 200, 30);
        jButton14.setBounds(0, 180, 200, 30);
        jButton15.setBounds(0, 90, 200, 30);
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here:
        jPanel6.setSize(jPanel6.getWidth(),30);
        jPanel4.setSize(jPanel4.getWidth(),30);
        jButton12.setBounds(0, 120, 200, 30);
        jButton13.setBounds(0, 150, 200, 30);
        jButton14.setBounds(0, 180, 200, 30);
        jButton15.setBounds(0, 90, 200, 30);
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        
        jPanel5.add(route);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jPanel5.removeAll();
        jPanel5.repaint();
        jPanel5.revalidate();
        
        jPanel5.add(search);
        jPanel5.repaint();
        jPanel5.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Cancel_UserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_UserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cancel_UserIDActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        conn = MyConnection.getConnection();
        
        String review = review_area.getText();
        
        String query = " INSERT INTO Review (Reviews) VALUES (?)" ;
        
        try {
            ps = conn.prepareStatement(query);
            
            ps.setString(1,review);
            
            if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null,"Reviews Listed !");
                    review_area.setText("");
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        conn = MyConnection.getConnection();
        
        String cancel_ID = Cancel_UserID.getText();
        
        String query = " INSERT INTO Cancell_request (UserID) VALUES (?)" ;
        
        try {
            ps = conn.prepareStatement(query);
            
            ps.setString(1,cancel_ID);
            
            if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null,"Request sucessfully registered !"
                       +"\n"     + "You will be contacted through mail");
                    Cancel_UserID.setText("");
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        conn = MyConnection.getConnection();
        
        String User_ID_rent = jText_UserID.getText();
        String Bus_amount =  (String)jCombo_No.getSelectedItem();
        String date_rent= jText_Date.getText();
        
        String query = " INSERT INTO Renting (UserID,Date,No_bus) VALUES (?,?,?)" ;
        
        try {
            ps = conn.prepareStatement(query);
            
            ps.setString(1,User_ID_rent);
            ps.setString(3,Bus_amount);
            ps.setString(2,date_rent);
            
            if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null,"Request sucessfully registered !"
                       +"\n"     + "You will be contacted through mail");
                    jText_UserID.setText("");
                    jText_Date.setText("");
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        conn = MyConnection.getConnection();
        
        String User_ID = jTextField2.getText();
        String Bus_amount =  (String)jComboBox3.getSelectedItem();
        String date= jTextField3.getText();
        String Type = "Gymkhana";
        
        String query = " INSERT INTO Booking (UserID,No_bus,Date,Type_of_User) VALUES (?,?,?,?)" ;
        
        try {
            ps = conn.prepareStatement(query);
            
            ps.setString(1,User_ID);
            ps.setString(2,Bus_amount);
            ps.setString(3,date);
            ps.setString(4,Type);
            
            if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null,"Request sucessfully registered !"
                       +"\n"     + "You will be contacted through mail");
                    jTextField2.setText("");
                    jTextField3.setText("");
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        conn = MyConnection.getConnection();
        
        String User_ID = jTextField4.getText();
        String Bus_amount =  (String)jComboBox4.getSelectedItem();
        String date= jTextField5.getText();
        String Type = "Department";
        
        String query = " INSERT INTO Booking (UserID,No_bus,Date,Type_of_User) VALUES (?,?,?,?)" ;
        
        try {
            ps = conn.prepareStatement(query);
            
            ps.setString(1,User_ID);
            ps.setString(2,Bus_amount);
            ps.setString(3,date);
            ps.setString(4,Type);
            
            if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null,"Request sucessfully registered !"
                       +"\n"     + "You will be contacted through mail");
                    jTextField4.setText("");
                    jTextField5.setText("");
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        conn = MyConnection.getConnection();
        
        String User_ID = jTextField6.getText();
        String Bus_amount =  (String)jComboBox5.getSelectedItem();
        String date= jTextField8.getText();
        String Type = "Social Cultural Event";
        
        String query = " INSERT INTO Booking (UserID,No_bus,Date,Type_of_User) VALUES (?,?,?,?)" ;
        
        try {
            ps = conn.prepareStatement(query);
            
            ps.setString(1,User_ID);
            ps.setString(2,Bus_amount);
            ps.setString(3,date);
            ps.setString(4,Type);
            
            if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null,"Request sucessfully registered !"
                       +"\n"     + "You will be contacted through mail");
                    jTextField6.setText("");
                    jTextField8.setText("");
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        conn = MyConnection.getConnection();
        
        String User_ID = jTextField7.getText();
        String Bus_amount =  (String)jComboBox6.getSelectedItem();
        String date= jTextField9.getText();
        String Type = "Society Event";
        
        String query = " INSERT INTO Booking (UserID,No_bus,Date,Type_of_User) VALUES (?,?,?,?)" ;
        
        try {
            ps = conn.prepareStatement(query);
            
            ps.setString(1,User_ID);
            ps.setString(2,Bus_amount);
            ps.setString(3,date);
            ps.setString(4,Type);
            
            if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null,"Request sucessfully registered !"
                       +"\n"     + "You will be contacted through mail");
                    jTextField7.setText("");
                    jTextField9.setText("");
                }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
      /*  String start = (String)jComboBox1.getSelectedItem();
        String stop = (String)jComboBox2.getSelectedItem();
        
        conn = MyConnection.getConnection();
        
        String query = " SELECT * FROM Bus_info WHERE " ;
        
        try {
            ps = conn.prepareStatement(query);
            
            ps.setString(1,start);
            ps.setString(2,stop);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
        */

    }//GEN-LAST:event_jButton18ActionPerformed


    //,t2 ;
    //Integer p1=30,p2=30;
//    
    /**
     * @param args the command line arguments
     */    
//    ActionListener a1=new ActionListener(){
//        public void actionPerformed(ActionEvent e){
//            if(p1>150){
//            t1.stop();
//            }
//            else{
//            jPanel4.setSize(jPanel4.getWidth(),p1);
//            p1+=10;
//            }
//        }
//    };
//    
//    ActionListener a2=new ActionListener(){
//        public void actionPerformed(ActionEvent e){
//            if(p2>150){
//            t2.stop();
//            }
//            else{
//            jPanel6.setSize(jPanel6.getWidth(),p2);
//            p2+=10;
//            }
//        }
//    };
//    
//    Timer t1= new Timer(50,a1);
//    Timer t2= new Timer(50,a2);
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cancel_UserID;
    private javax.swing.JPanel Occasion;
    private javax.swing.JPanel allBuses;
    private javax.swing.JPanel cancel;
    private javax.swing.JPanel departmentBooking;
    private javax.swing.JPanel gymkhanaBooking;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JComboBox<String> jCombo_No;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane_Review;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jText_Date;
    private javax.swing.JTextField jText_UserID;
    private javax.swing.JPanel rent;
    private javax.swing.JTextArea review_area;
    private javax.swing.JPanel reviews;
    private javax.swing.JPanel route;
    private javax.swing.JPanel search;
    private javax.swing.JPanel societyBooking;
    private javax.swing.JPanel socultBooking;
    private javax.swing.JPanel stop;
    // End of variables declaration//GEN-END:variables

    

    
}
